// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIFbJx9aeF7pd5ELbO4XqOjkY518wTla0',
    appId: '1:1024204083698:web:55591436ba8cb8c6f81b6b',
    messagingSenderId: '1024204083698',
    projectId: 'sjsapp-b0296',
    authDomain: 'sjsapp-b0296.firebaseapp.com',
    storageBucket: 'sjsapp-b0296.appspot.com',
    measurementId: 'G-17TSR54XT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSyoXv4Ro_cJl4aGLl6XYoPcnde1g-0C8',
    appId: '1:1024204083698:android:a595bce430701d77f81b6b',
    messagingSenderId: '1024204083698',
    projectId: 'sjsapp-b0296',
    storageBucket: 'sjsapp-b0296.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEgFJgg3QST3PFi9JRAV3CWGLWhh1bEQc',
    appId: '1:1024204083698:ios:de1b03f8505dd4c1f81b6b',
    messagingSenderId: '1024204083698',
    projectId: 'sjsapp-b0296',
    storageBucket: 'sjsapp-b0296.appspot.com',
    iosBundleId: 'com.example.sjsApp',
  );
}
